name: Build and Test .NET 5 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build
      run: |
        dotnet build src/nuSpec.Abstraction/nuSpec.Abstraction.csproj  --configuration Release
        dotnet build src/nuSpec.NHibernate/nuSpec.NHibernate.csproj  --configuration Release
        dotnet build src/nuSpec.Tests/nuSpec.Tests.csproj  --configuration Release
    - name: Test
      run: dotnet test src/nuSpec.Tests/nuSpec.Tests.csproj --no-build --verbosity normal
